### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by marek-j** [mwganson/DynamicData#83]
Hi, I installed DynamicData v2.69.0 through the AddonManager into FreeCAD Link Branch 2024.1003.0 (Realthunder) as a Snap on Linux Mint 22. After a restart of FreeCAD I create a DD with the DD workbench and I get the following error as a popup and in the report view respectively:
![image](https://github.com/user-attachments/assets/524925bf-f37c-49b5-b36e-fa17b4b518dc)

```
09:36:34  Traceback (most recent call last):
  File "<string>", line 86, in Activated
  File "/snap/freecad-realthunder/133/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)

09:36:34  No module named 'requests'
```

From then on everything seems to work fine but the same error message comes up every time I exit a sketch.

**Comment by mwganson** [comment]
I just pushed an update to verison 2.70.  It should not just print a warning message that the requests package module is not available.  You can disable the warnings by disabling automatic update checking in Dynamic Data settings.

You can also try to install the requests package into the FreeCAD environment.  There is a macro that can potentially help with that here: https://forum.freecad.org/viewtopic.php?t=91793
